kind: Service
apiVersion: v1
metadata:
  name: bitcoin-cash-rpc
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  selector:
    app: bitcoin-cash
  ports:
    - protocol: TCP
      port: 18332
      targetPort: 18332
      name: rpc
  type: LoadBalancer
