kind: Service
apiVersion: v1
metadata:
  name: bitcoin-cash-rpc
spec:
  selector:
    app: bitcoin-cash
  ports:
    - protocol: TCP
      port: 18332
      targetPort: 18332
      name: rpc
  type: ClusterIP
