apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: bitcoin-cash
  name: bitcoin-cash
spec:
  replicas: 1
  serviceName: bitcoin-cash
  template:
    metadata:
      annotations:
        prometheus.io/port: "9113"
        prometheus.io/scrape: "true"
      labels:
        app: bitcoin-cash
        network: testnet
        blockchain: bitcoin-cash-abc
    spec:
      containers:
      - args:
        - bitcoind
        - -server
        - -testnet
        - -printtoconsole
        - -debug=rpc
        - -externalip=35.229.29.176
        - -txindex
        - -datadir=/data
        - -rpcuser=$(BITCOIN_RPC_USER)
        - -rpcpassword=$(BITCOIN_RPC_PASSWORD)
        - -rpcport=18332
        - -rpcbind=0.0.0.0
        - -rpcallowip=0.0.0.0/0
        envFrom:
          - secretRef:
              name: node-credentials
        env:
        - name: BITCOIN_ABC_DATA
          value: /data/testnet3
        image: us.gcr.io/ops-support-191021/bitcoin-cash:v0.19.5
        imagePullPolicy: Always
        name: bitcoin-cash
        ports:
        - containerPort: 18332
          name: listener
          protocol: TCP
        - containerPort: 18333
          name: rpc
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 7000Mi
          requests:
            cpu: 100m
            memory: 6500Mi
        volumeMounts:
        - mountPath: /data
          name: storage
      - args:
        - -namespace=bitcoin
        - -rpc.user=$(BITCOIN_RPC_USER)
        - -rpc.pass=$(BITCOIN_RPC_PASSWORD)
        - -rpc.host=127.0.0.1:18332
        envFrom:
          - secretRef:
              name: node-credentials
        image: platanus/bitcoin-prometheus-exporter:0.2.0
        name: bitcoin-prometheus-exporter
        ports:
        - containerPort: 9113
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 150Mi
          requests:
            cpu: 20m
            memory: 30Mi
      terminationGracePeriodSeconds: 60
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: standard